services:
  # Entorno interactivo para debugging manual
  interactive:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true 
    tty: true        
    entrypoint: ["/bin/bash"] 

  # Ejecutor de la suite de pruebas core
  c-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    entrypoint: ["make", "test", "CC=clang"]